# Generated by Django 5.0.6 on 2024-08-17 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transportation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('food', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entertainment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('personal_care', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debt_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('savings', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Expenditures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_budget.expenses')),
            ],
        ),
    ]
